#!/usr/bin/env bash
#####################################################
# Source Generated by nginxconfig.io
# Updated by cryptopool.builders for crypto use...
#
# Writes the nginx site for the YiiMP web front end and requests the
# Let's Encrypt certificate. This file only defines functions; it replaces
# the former nginx_(sub)domain_(non)ssl.sh scripts.
#####################################################

# Prints the "listen"/"http2" lines for an SSL server block. nginx 1.25.1
# deprecated "listen ... http2" in favour of the "http2" directive.
function mp_nginx_listen_ssl {
	local version
	version=$(nginx -v 2>&1 | sed -n 's|.*nginx/\([0-9.]*\).*|\1|p')
	if [ -n "$version" ] && [ "$(printf '%s\n' 1.25.1 "$version" | sort -V | head -n 1)" = "1.25.1" ]; then
		printf '\tlisten 443 ssl;\n\tlisten [::]:443 ssl;\n\thttp2 on;\n'
	else
		printf '\tlisten 443 ssl http2;\n\tlisten [::]:443 ssl http2;\n'
	fi
}

# mp_nginx_site self|letsencrypt
# Write /etc/nginx/sites-available/$DomainName.conf using either the self
# signed certificate or the Let's Encrypt certificate, and enable it.
function mp_nginx_site {
	local mode=$1
	local conf="/etc/nginx/sites-available/${DomainName}.conf"
	local server_names=$DomainName cert key extra=""

	if ! is_yes "${UsingSubDomain:-no}"; then
		server_names="${DomainName} www.${DomainName}"
	fi
	if [ "$mode" = "letsencrypt" ]; then
		cert="/etc/letsencrypt/live/${DomainName}/fullchain.pem"
		key="/etc/letsencrypt/live/${DomainName}/privkey.pem"
		extra=$(printf '\tssl_trusted_certificate /etc/letsencrypt/live/%s/chain.pem;\n\n\t# HSTS, only with a certificate browsers trust\n\tadd_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;' "$DomainName")
	else
		cert="${STORAGE_ROOT}/ssl/ssl_certificate.pem"
		key="${STORAGE_ROOT}/ssl/ssl_private_key.pem"
	fi

	sudo tee "$conf" > /dev/null <<EOF
#####################################################
# Source Generated by nginxconfig.io
# Updated by cryptopool.builders for crypto use...
#####################################################

# NGINX Simple DDoS Defense
limit_conn_zone \$binary_remote_addr zone=conn_limit_per_ip:10m;
limit_req_zone \$binary_remote_addr zone=req_limit_per_ip:40m rate=5r/s;

server {
$(mp_nginx_listen_ssl)

	server_name ${server_names};
	set \$base "/var/www/${DomainName}/html";
	root \$base/web;

	limit_conn conn_limit_per_ip 80;
	limit_req zone=req_limit_per_ip burst=80 nodelay;

	# SSL
	ssl_certificate ${cert};
	ssl_certificate_key ${key};
${extra}

	# security
	include cryptopool.builders/security.conf;

	# logging
	access_log ${STORAGE_ROOT}/yiimp/site/log/${DomainName}.app.access.log;
	error_log ${STORAGE_ROOT}/yiimp/site/log/${DomainName}.app.error.log warn;

	# index.php
	index index.php;

	# index.php fallback
	location / {
		try_files \$uri \$uri/ /index.php?\$args;
	}
	location @rewrite {
		rewrite ^/(.*)\$ /index.php?r=\$1;
	}

	# handle .php
	location ~ \.php\$ {
		include cryptopool.builders/php_fastcgi.conf;
	}

	# additional config
	include cryptopool.builders/general.conf;
}

# HTTP redirect
server {
	listen 80;
	listen [::]:80;

	server_name .${DomainName};

	include cryptopool.builders/letsencrypt.conf;

	location / {
		return 301 https://${DomainName}\$request_uri;
	}
}
EOF
	sudo ln -sfn "$conf" "/etc/nginx/sites-enabled/${DomainName}.conf"
	sudo mkdir -p "/var/www/${DomainName}/html"
	sudo ln -sfn "$STORAGE_ROOT/yiimp/site/web" "/var/www/${DomainName}/html/web"

	if ! sudo nginx -t > /dev/null 2>&1; then
		echo -e "$RED The generated nginx configuration is invalid:$COL_RESET"
		sudo nginx -t
		return 1
	fi
	restart_service nginx
	restart_service "php${PHP_VERSION}-fpm"
}

# Request a Let's Encrypt certificate for $DomainName with the webroot
# plugin. Returns failure (and keeps the self signed site) if it fails.
function mp_certbot {
	local email_args=(--register-unsafely-without-email)
	if [[ "${SupportEmail:-}" == *@*.* ]]; then
		email_args=(-m "$SupportEmail")
	fi

	echo -e " Generating Certbot Request for ${DomainName} ...$COL_RESET"
	sudo mkdir -p /var/www/_letsencrypt
	sudo chown www-data /var/www/_letsencrypt
	if ! sudo certbot certonly --webroot -w /var/www/_letsencrypt -d "$DomainName" \
		"${email_args[@]}" -n --agree-tos --keep-until-expiring > /dev/null 2>&1 \
		|| ! sudo test -f "/etc/letsencrypt/live/${DomainName}/fullchain.pem"; then
		echo -e "$RED Certbot generation failed, after the installer is finished check /var/log/letsencrypt (must be root to view) on why it failed.$COL_RESET"
		return 1
	fi

	# Reload nginx after a successful renewal
	sudo mkdir -p /etc/letsencrypt/renewal-hooks/deploy
	printf '#!/bin/sh\nnginx -t && systemctl reload nginx\n' \
		| sudo tee /etc/letsencrypt/renewal-hooks/deploy/nginx-reload.sh > /dev/null
	sudo chmod 0755 /etc/letsencrypt/renewal-hooks/deploy/nginx-reload.sh
	echo -e "$GREEN Done...$COL_RESET"
}
