#!/usr/bin/env bash
#####################################################
# Created by cryptopool.builders for crypto use...
#
# Installed as /usr/bin/addport_multi: adds a dedicated coin port on this
# stratum server and on the other stratum servers listed (one user@ip per
# line) in $STORAGE_ROOT/yiimp/.remote_stratums.conf. SSH asks for each
# server's password unless you use SSH keys; no passwords are stored.
#####################################################

exec /usr/bin/addport --multi "$@"
