#!/usr/bin/env bash
#####################################################
# Dedicated Port config generator
# Created by cryptopool.builders for multipool
# This generator will modify the main algo.conf file
# Create the new coin.algo.conf file
# And update the stratum start file
#
#   addport            add the port on this stratum server
#   addport --multi    also add it on the stratum servers listed in
#                      $STORAGE_ROOT/yiimp/.remote_stratums.conf
#                      (installed as addport_multi)
#####################################################

source /etc/functions.sh
source /etc/multipool.conf

multi=false
if [ "${1:-}" = "--multi" ]; then
	multi=true
fi

config_dir="$STORAGE_ROOT/yiimp/site/stratum/config"
remote_script="$STORAGE_ROOT/yiimp/remote.sh"
remote_list="$STORAGE_ROOT/yiimp/.remote_stratums.conf"

clear

# Pick a random port between 2768 and 6999 that nothing listens on yet.
function ephemeral_port {
	local port
	while true; do
		port=$((2768 + RANDOM % (6999 - 2768 + 1)))
		if ! ss -Hltn "sport = :${port}" | grep -q .; then
			echo "$port"
			return 0
		fi
	done
}

cd "$config_dir" || exit 1
echo "Thanks for using the addport script by cryptopool.builders."
echo
echo "addport will randomly selects an open port for the coin between ports 2768 and 6999 and open the port in UFW."
echo "It will also create a new symbol.algo.conf in $config_dir"
echo "and will create a new stratum.symbol run file in /usr/bin."
echo

echo
echo -e "$RED Make sure coin symbol is all UPPER case.$COL_RESET"
coinsymbol=
while ! [[ "$coinsymbol" =~ ^[A-Za-z0-9]+$ ]]; do
	read -r -e -p "Please enter the coin SYMBOL : " coinsymbol
done
echo ""
echo -e "$RED Make sure algo is in all lower case and a valid algo in yiimp.$COL_RESET"
coinalgo=
while ! [[ "$coinalgo" =~ ^[A-Za-z0-9]+$ ]]; do
	read -r -e -p "Please enter the coin algo : " coinalgo
done
echo ""
nicevalue=
read -r -e -p "Would you like to set a minimum nicehash value for this stratum? (y/n) : " nicehash
if [[ "${nicehash,,}" == "y" || "${nicehash,,}" == "yes" ]]; then
	while ! [[ "$nicevalue" =~ ^[0-9]+$ ]]; do
		read -r -e -p "Please enter a whole value, example: 750000 : " nicevalue
	done
fi
# make sure algo is lower as well since we are Here
coinalgo=${coinalgo,,}
# and might as well make sure the symbol is upper case
coinsymbol=${coinsymbol^^}
# Make the coin symbol lower case
coinsymbollower=${coinsymbol,,}

# Make sure the algo file exists.
if [ ! -f "$config_dir/$coinalgo.conf" ]; then
	echo -e "Sorry that algo config file doesn't exist in $config_dir please double check and try again."
	exit 0
fi

# Make sure the stratum.symbol config doesnt exist.
if [ -f "$config_dir/stratum.${coinsymbollower}" ]; then
	read -r -e -p "A file for ${coinsymbol} already exists. Are you sure you want to overwrite? A new port will be generated and you will need to update your coind.conf blocknotify line (y/n) : " overwrite
	if [[ "${overwrite,,}" != "y" && "${overwrite,,}" != "yes" ]]; then
		echo -e "Later gator..."
		exit 0
	fi
fi

coinport=$(ephemeral_port)
args=("$coinsymbol" "$coinalgo" "$coinport")
if [ -n "$nicevalue" ]; then
	args+=("$nicevalue")
fi

echo
echo -e "$YELLOW Starting your new stratum...$COL_RESET"
bash "$remote_script" "${args[@]}" || exit 1
echo -e "$GREEN Your new stratum is started...Do NOT run the start command manually...$COL_RESET"

if [ "$multi" = true ]; then
	echo "Adding port and config files to remote stratums, script will seem to hang for a few minutes..."
	if [ ! -f "$remote_list" ]; then
		echo -e "$RED No remote stratum servers configured.$COL_RESET"
		echo "List them in $remote_list, one user@private_ip per line, then run addport_multi again."
	else
		while read -r server _; do
			[[ -z "$server" || "$server" == \#* ]] && continue
			echo -e "$YELLOW Updating ${server}...$COL_RESET"
			# You are asked for the password of each server unless you use SSH keys.
			# shellcheck disable=SC2029
			if ! ssh -o StrictHostKeyChecking=accept-new "$server" "bash -s -- $(printf '%q ' "${args[@]}")" < "$remote_script"; then
				echo -e "$RED Updating ${server} failed.$COL_RESET"
			fi
		done < <(grep -v '^[[:space:]]*$' "$remote_list")
		echo "Addport is completed and all stratums have been updated and the stratums have been started."
	fi
fi

echo
echo -e "To use your new stratum type,$BLUE stratum.${coinsymbollower} start|stop|restart ${coinsymbollower} $COL_RESET"
echo
echo -e "To see the stratum screen type,$MAGENTA screen -r ${coinsymbollower} $COL_RESET"
echo
echo -e "The assigned dedicated port for this coins stratum is :$YELLOW $coinport $COL_RESET"
echo
echo "Make sure to add this to the Dedicated Port section in your YiiMP admin area!"
echo "You must update your coin.conf on your DAEMON server(s) for blocknotify to use this new port : $coinport"
echo "If you do not update this you will get blocknotify errors!"
echo

echo "Donations for continued support of this script are welcomed at:"
echo
echo "BTC 3DvcaPT3Kio8Hgyw4ZA9y1feNnKZjH7Y21"
echo "BCH qrf2fhk2pfka5k649826z4683tuqehaq2sc65nfz3e"
echo "ETH 0x6A047e5410f433FDBF32D7fb118B6246E3b7C136"
echo "LTC MLS5pfgb7QMqBm3pmBvuJ7eRCRgwLV25Nz"

cd ~ || exit 0
exit 0
