#!/usr/bin/env bash
#####################################################
# Source code from https://codereview.stackexchange.com/questions/55077/small-bash-script-to-start-and-stop-named-services
# Updated by cryptopool.builders for crypto use...
#
# Start/stop the YiiMP screens on the web server:
#   screens start|stop|restart main|loop2|blocks|debug
#####################################################

source /etc/multipool.conf
source "$STORAGE_ROOT/yiimp/.prescreens.start.conf"

function screen_start {
	case "$1" in
		main | loop2 | blocks) screen -dmS "$1" bash "${CRONS}/$1.sh" ;;
		debug) screen -dmS debug tail -f "${LOG_DIR}/debug.log" ;;
	esac
}

function screen_stop {
	screen -X -S "$1" quit
}

function startstop_service {
	sudo systemctl "$1" "$2"
}

case "${1:-}" in
	start | stop | restart) cmd=$1 ;;
	*)
		echo "usage: $0 [start|stop|restart] main|loop2|blocks|debug"
		exit 1
		;;
esac
shift

for name; do
	case "$name" in
		main | loop2 | blocks | debug)
			case "$cmd" in
				start) screen_start "$name" ;;
				stop) screen_stop "$name" ;;
				restart)
					screen_stop "$name"
					sleep 1
					screen_start "$name"
					;;
			esac
			;;
		*) startstop_service "$cmd" "$name" ;;
	esac
done
