#!/usr/bin/env bash
#####################################################
# Source code from https://codereview.stackexchange.com/questions/55077/small-bash-script-to-start-and-stop-named-services
# Updated by cryptopool.builders for crypto use...
#
# Start/stop the stratum for an algo:
#   stratum start|stop|restart algo [algo...]
#####################################################

source /etc/multipool.conf
STRATUM_DIR=$STORAGE_ROOT/yiimp/site/stratum
export LOG_DIR=$STORAGE_ROOT/yiimp/site/log

# screen name => config file (in $STRATUM_DIR/config, without .conf)
declare -A ALGOS=(
	[sha256]=sha [sha256t]=sha256t [lbry]=lbry [scrypt]=scrypt [timetravel]=timetravel
	[bitcore]=bitcore [exosis]=exosis [c11]=c11 [deep]=deep [x11]=x11 [x11evo]=x11evo [x12]=x12
	[x13]=x13 [x15]=x15 [x16r]=x16r [x16s]=x16s [x17]=x17 [x22i]=x22i [aergo]=aergo [xevan]=xevan
	[hmq1725]=hmq1725 [nist5]=nist5 [x14]=x14 [quark]=quark [whirlpool]=whirlpool
	[neoscrypt]=neoscrypt [argon2]=argon2 [argon2ddyn]=argon2ddyn [scryptn]=scryptn [allium]=allium
	[lbk3]=lbk3 [lyra2]=lyra2 [lyra2v2]=lyra2v2 [lyra2z]=lyra2z [jha]=jha [qubit]=qubit [zr5]=zr5
	[skein]=skein [sib]=sib [keccak]=keccak [keccakc]=keccakc [hex]=hex [skein2]=skein2 [dmdgr]=dmdgr
	[myrgr]=myrgr [blake]=blake [blakecoin]=blakecoin [decred]=decred [vanilla]=vanilla
	[blake2s]=blake2s [penta]=penta [rainforest]=rainforest [luffa]=luffa [m7m]=m7m [veltor]=veltor
	[velvet]=velvet [vitalium]=vitalium [yescrypt]=yescrypt [yescryptR16]=yescryptR16
	[yescryptR32]=yescryptR32 [bastion]=bastion [hsr]=hsr [phi]=phi [phi2]=phi2 [polytimos]=polytimos
	[skunk]=skunk [tribus]=tribus [a5a]=a5a [x16rv2]=x16rv2
)

function stratum_start {
	screen -dmS "$1" bash "$STRATUM_DIR/run.sh" "${ALGOS[$1]}"
}

function stratum_stop {
	screen -X -S "$1" quit
}

function startstop_service {
	sudo systemctl "$1" "$2"
}

case "${1:-}" in
	start | stop | restart) cmd=$1 ;;
	*)
		echo "usage: $0 [start|stop|restart] algo"
		exit 1
		;;
esac
shift

for name; do
	if [ -n "${ALGOS[$name]:-}" ]; then
		case "$cmd" in
			start) stratum_start "$name" ;;
			stop) stratum_stop "$name" ;;
			restart)
				stratum_stop "$name"
				sleep 1
				stratum_start "$name"
				;;
		esac
	else
		startstop_service "$cmd" "$name"
	fi
done
